server:
  port: 8080 # 项目启动端口

spring:
  ai:
    openai:
      base-url: https://llm-al9gjo71owh37s2d.cn-beijing.maas.aliyuncs.com/compatible-mode/v1 # OpenAI 服务的访问地址，这里使用的是阿里云百炼
      api-key: sk-ws-H.EXPHIXX.PR3p.MEYCIQDrnUXeL2Qz5K-rTMrPk-O34cVC1mpRskJ9oLQD_xE_hwIhAMaqJbDj6F2V34Pgu8a8QkpK1E9IBYUAnsmGNL12jm7T  # 填写阿里云百炼的 API Key, 改成你自己的
